/*
 * Minimal d3dkmthk.h compatibility shim for mingw-w64 / ARM64EC builds.
 *
 * mingw-w64 ships no D3DKMT (WDDM kernel thunk) headers, so this declares
 * only the subset OptiScaler actually uses:
 *   - Util.cpp            : adapter enumeration + UMD driver path lookup
 *   - hooks/Gdi32_Hooks.h : HAGS (hardware scheduling) spoofing
 *
 * The KMTQUERYADAPTERINFOTYPE enumerators are ordinal-sensitive (they are
 * matched against values produced by the real gdi32), so the list is taken
 * verbatim from Wine's include/ddk/d3dkmthk.h to guarantee correct values.
 * That file is Copyright 2016 Henri Verbeet for CodeWeavers, LGPL-2.1-or-later,
 * which is compatible with OptiScaler's GPL-3.0.
 *
 * All D3DKMT entry points are resolved at runtime via GetProcAddress /
 * DetourFindFunction, so no import library is required; the prototypes exist
 * purely so decltype(&D3DKMTxxx) works.
 */
#ifndef OPTISCALER_COMPAT_D3DKMTHK_H
#define OPTISCALER_COMPAT_D3DKMTHK_H

#include <windows.h>

#ifndef MAX_PATH
#define MAX_PATH 260
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef UINT32 D3DKMT_HANDLE;

typedef enum _KMTQUERYADAPTERINFOTYPE
{
    KMTQAITYPE_UMDRIVERPRIVATE,
    KMTQAITYPE_UMDRIVERNAME,
    KMTQAITYPE_UMOPENGLINFO,
    KMTQAITYPE_GETSEGMENTSIZE,
    KMTQAITYPE_ADAPTERGUID,
    KMTQAITYPE_FLIPQUEUEINFO,
    KMTQAITYPE_ADAPTERADDRESS,
    KMTQAITYPE_SETWORKINGSETINFO,
    KMTQAITYPE_ADAPTERREGISTRYINFO,
    KMTQAITYPE_CURRENTDISPLAYMODE,
    KMTQAITYPE_MODELIST,
    KMTQAITYPE_CHECKDRIVERUPDATESTATUS,
    KMTQAITYPE_VIRTUALADDRESSINFO,
    KMTQAITYPE_DRIVERVERSION = 13,
    KMTQAITYPE_ADAPTERTYPE = 15,
    KMTQAITYPE_OUTPUTDUPLCONTEXTSCOUNT,
    KMTQAITYPE_WDDM_1_2_CAPS,
    KMTQAITYPE_UMD_DRIVER_VERSION,
    KMTQAITYPE_DIRECTFLIP_SUPPORT,
    KMTQAITYPE_MULTIPLANEOVERLAY_SUPPORT,
    KMTQAITYPE_DLIST_DRIVER_NAME,
    KMTQAITYPE_WDDM_1_3_CAPS,
    KMTQAITYPE_MULTIPLANEOVERLAY_HUD_SUPPORT,
    KMTQAITYPE_WDDM_2_0_CAPS,
    KMTQAITYPE_NODEMETADATA,
    KMTQAITYPE_CPDRIVERNAME,
    KMTQAITYPE_XBOX,
    KMTQAITYPE_INDEPENDENTFLIP_SUPPORT,
    KMTQAITYPE_MIRACASTCOMPANIONDRIVERNAME,
    KMTQAITYPE_PHYSICALADAPTERCOUNT,
    KMTQAITYPE_PHYSICALADAPTERDEVICEIDS,
    KMTQAITYPE_DRIVERCAPS_EXT,
    KMTQAITYPE_QUERY_MIRACAST_DRIVER_TYPE,
    KMTQAITYPE_QUERY_GPUMMU_CAPS,
    KMTQAITYPE_QUERY_MULTIPLANEOVERLAY_DECODE_SUPPORT,
    KMTQAITYPE_QUERY_HW_PROTECTION_TEARDOWN_COUNT,
    KMTQAITYPE_QUERY_ISBADDRIVERFORHWPROTECTIONDISABLED,
    KMTQAITYPE_MULTIPLANEOVERLAY_SECONDARY_SUPPORT,
    KMTQAITYPE_INDEPENDENTFLIP_SECONDARY_SUPPORT,
    KMTQAITYPE_PANELFITTER_SUPPORT,
    KMTQAITYPE_PHYSICALADAPTERPNPKEY,
    KMTQAITYPE_GETSEGMENTGROUPSIZE,
    KMTQAITYPE_MPO3DDI_SUPPORT,
    KMTQAITYPE_HWDRM_SUPPORT,
    KMTQAITYPE_MPOKERNELCAPS_SUPPORT,
    KMTQAITYPE_MULTIPLANEOVERLAY_STRETCH_SUPPORT,
    KMTQAITYPE_GET_DEVICE_VIDPN_OWNERSHIP_INFO,
    KMTQAITYPE_QUERYREGISTRY,
    KMTQAITYPE_KMD_DRIVER_VERSION,
    KMTQAITYPE_BLOCKLIST_KERNEL,
    KMTQAITYPE_BLOCKLIST_RUNTIME,
    KMTQAITYPE_ADAPTERGUID_RENDER,
    KMTQAITYPE_ADAPTERADDRESS_RENDER,
    KMTQAITYPE_ADAPTERREGISTRYINFO_RENDER,
    KMTQAITYPE_CHECKDRIVERUPDATESTATUS_RENDER,
    KMTQAITYPE_DRIVERVERSION_RENDER,
    KMTQAITYPE_ADAPTERTYPE_RENDER,
    KMTQAITYPE_WDDM_1_2_CAPS_RENDER,
    KMTQAITYPE_WDDM_1_3_CAPS_RENDER,
    KMTQAITYPE_QUERY_ADAPTER_UNIQUE_GUID,
    KMTQAITYPE_NODEPERFDATA,
    KMTQAITYPE_ADAPTERPERFDATA,
    KMTQAITYPE_ADAPTERPERFDATA_CAPS,
    KMTQUITYPE_GPUVERSION,
    KMTQAITYPE_DRIVER_DESCRIPTION,
    KMTQAITYPE_DRIVER_DESCRIPTION_RENDER,
    KMTQAITYPE_SCANOUT_CAPS,
    KMTQAITYPE_PARAVIRTUALIZATION_RENDER,
    KMTQAITYPE_SERVICENAME,
    KMTQAITYPE_WDDM_2_7_CAPS,
    KMTQAITYPE_DISPLAY_UMDRIVERNAME = 71,
    KMTQAITYPE_TRACKEDWORKLOAD_SUPPORT,
    KMTQAITYPE_HYBRID_DLIST_DLL_SUPPORT,
    KMTQAITYPE_DISPLAY_CAPS,
    KMTQAITYPE_WDDM_2_9_CAPS,
    KMTQAITYPE_CROSSADAPTERRESOURCE_SUPPORT,
    KMTQAITYPE_WDDM_3_0_CAPS,
    KMTQAITYPE_WSAUMDIMAGENAME,
    KMTQAITYPE_VGPUINTERFACEID,
    KMTQAITYPE_WDDM_3_1_CAPS
} KMTQUERYADAPTERINFOTYPE;

typedef struct _D3DKMT_ADAPTERINFO
{
    D3DKMT_HANDLE hAdapter;
    LUID          AdapterLuid;
    ULONG         NumOfSources;
    BOOL          bPrecisePresentRegionsPreferred;
} D3DKMT_ADAPTERINFO;

#define MAX_ENUM_ADAPTERS 16

typedef struct _D3DKMT_ENUMADAPTERS
{
    ULONG             NumAdapters;
    D3DKMT_ADAPTERINFO Adapters[MAX_ENUM_ADAPTERS];
} D3DKMT_ENUMADAPTERS;

typedef struct _D3DKMT_ENUMADAPTERS2
{
    ULONG              NumAdapters;
    D3DKMT_ADAPTERINFO *pAdapters;
} D3DKMT_ENUMADAPTERS2;

typedef struct _D3DKMT_CLOSEADAPTER
{
    D3DKMT_HANDLE hAdapter;
} D3DKMT_CLOSEADAPTER;

typedef struct _D3DKMT_QUERYADAPTERINFO
{
    D3DKMT_HANDLE            hAdapter;
    KMTQUERYADAPTERINFOTYPE  Type;
    VOID                    *pPrivateDriverData;
    UINT                     PrivateDriverDataSize;
} D3DKMT_QUERYADAPTERINFO;

typedef enum _KMTUMDVERSION
{
    KMTUMDVERSION_DX9 = 0,
    KMTUMDVERSION_DX10,
    KMTUMDVERSION_DX11,
    KMTUMDVERSION_DX12,
    NUM_KMTUMDVERSIONS
} KMTUMDVERSION;

typedef struct _D3DKMT_UMDFILENAMEINFO
{
    KMTUMDVERSION Version;
    WCHAR         UmdFileName[MAX_PATH];
} D3DKMT_UMDFILENAMEINFO;

typedef enum _DXGK_FEATURE_SUPPORT_STATUS
{
    DXGK_FEATURE_SUPPORT_ALWAYS_OFF      = 0,
    DXGK_FEATURE_SUPPORT_EXPERIMENTAL    = 1,
    DXGK_FEATURE_SUPPORT_STABLE          = 2,
    DXGK_FEATURE_SUPPORT_ALWAYS_ON       = 3
} DXGK_FEATURE_SUPPORT_STATUS;

typedef struct _D3DKMT_WDDM_2_7_CAPS
{
    union {
        struct {
            UINT HwSchSupported           : 1;
            UINT HwSchEnabled             : 1;
            UINT HwSchEnabledByDefault    : 1;
            UINT IndependentVidPnVSyncControl : 1;
            UINT Reserved                 : 28;
        };
        UINT Value;
    };
} D3DKMT_WDDM_2_7_CAPS;

typedef struct _D3DKMT_WDDM_2_9_CAPS
{
    union {
        struct {
            UINT HwSchSupportState        : 3;
            UINT HwSchEnabled             : 1;
            UINT SelfRefreshMemorySupported : 1;
            UINT Reserved                 : 27;
        };
        UINT Value;
    };
} D3DKMT_WDDM_2_9_CAPS;

NTSTATUS WINAPI D3DKMTEnumAdapters(D3DKMT_ENUMADAPTERS *pData);
NTSTATUS WINAPI D3DKMTEnumAdapters2(D3DKMT_ENUMADAPTERS2 *pData);
NTSTATUS WINAPI D3DKMTQueryAdapterInfo(const D3DKMT_QUERYADAPTERINFO *pData);
NTSTATUS WINAPI D3DKMTCloseAdapter(const D3DKMT_CLOSEADAPTER *pData);

#ifdef __cplusplus
}
#endif

#endif /* OPTISCALER_COMPAT_D3DKMTHK_H */
